"""User table

Revision ID: bea32d3a0d38
Revises: abf60d62e406
Create Date: 2022-01-21 20:07:06.825228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea32d3a0d38'
down_revision = 'abf60d62e406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('message', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('message_user_fkey', 'message', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_user_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
